POST http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: Aplication/json

{
    "id": 4,
    "titulo": "Aprende Node.js",
    "lenguaje": "JavaScript",
    "vistas": 55275,
    "nivel": "basico",
}

###
PUT http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: Aplication/json

{
    "id": 2,
    "titulo": "Python Intermedio con Proyectos",
    "lenguaje": "Python",
    "vistas": 472663,
    "nivel": "Intermedio",
}

###
PATCH http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
Content-Type: Aplication/json
{
    "titulo": "Python Intermedio con Proyectos";
    "vistas": 15154;
}

###
DELETE http://localhost:3000/api/cursos/programacion/2 HTTP/1.1
